### Introduction To Numpy 

#### Wait... why am I learning this again? I already know lists!

Untill now, we all know Python lists are powerful!
<ul>
    <li>They can hold collection of values</li>
    <li>They can hold different types of data</li>
    <li>We can change, add or remove the items inside of a list</li>
    </ul>
buttttt one important thing is missing.


**the ability to perform a mathematical operation over *all* the items at the same time**

Let's explore what I exactly mean by this.
We have the heights and weights of my family members right here:

In [1]:
heights = [1.73, 1.68, 1.79, 1.92, 1.50, 1.64]
weights = [90.0, 71.0, 55.0, 67.0, 99.2, 69]

If we want to calculate the BMI of each person, the fastest thing we hope that's gonna work would be the following:

In [2]:
weights/heights**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

oh oh :( Python has no idea what we're talking about. well no worries, that's why we have **Numpy**!

Numpy has its own array, which is an alternative for our regular Python lists. 
We simply call them **numpy arrays**


[in case you haven't installed numpy, run the following cell]

In [ ]:
!pip3 install numpy

In [3]:
import numpy as np

Let's *convert* our previous lists into numpy arrays and see if we can perform the one-liner in line2!

In [4]:
heights_np = np.array(heights)
heights_np

array([1.73, 1.68, 1.79, 1.92, 1.5 , 1.64])

In [5]:
weights_np = np.array(weights)
weights_np

array([90. , 71. , 55. , 67. , 99.2, 69. ])

In [6]:
weights_np/heights_np**2

array([30.07116843, 25.15589569, 17.16550669, 18.17491319, 44.08888889,
       25.6543724 ])

**Important Note : Numpy arrays can ONLY contain ONE data-type**

In [7]:
example = [2, 6.5, '4']

In [8]:
example_np = np.array(example)

In [9]:
example_np

array(['2', '6.5', '4'], dtype='<U32')

##### Sum of two numpy arrays

In [10]:
weights_np + heights_np

array([ 91.73,  72.68,  56.79,  68.92, 100.7 ,  70.64])

##### Numpy Array Subsetting

In [12]:
weights_np

array([90. , 71. , 55. , 67. , 99.2, 69. ])

In [11]:
weights_np[3]

67.0

#### Task 

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [13]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
# Import the numpy package as np
import numpy as np
np_baseball = np.array(baseball)
np_baseball





# import numpy as np
# # Create a numpy array from baseball: np_baseball
# np_baseball = np.array(baseball)
# # Print out type of np_baseball
# print(type(np_baseball))

array([180, 215, 210, 210, 188, 176, 209, 200])

In [ ]:
np_baseball

In [16]:
heights_in = [72, 74, 67, 69, 66, 68, 77, 70]

np_heights_in = np.array(heights_in)
np_heights_m = np_heights_in*0.0254
np_heights_m



# # Create a numpy array from height_in: np_height_in
# np_height_in = np.array(heights_in)
# # Print out np_height_in
# print(np_height_in)
# # Convert np_height_in to m: np_height_m
# #multiply by 0.0254
# np_height_m = np_height_in*0.0254
# # Print np_height_m
# np_height_m

array([1.8288, 1.8796, 1.7018, 1.7526, 1.6764, 1.7272, 1.9558, 1.778 ])

Use `np_height_m` and `np_weigh`t to calculate the **BMI** of each player. Use the following equation:
`weight/height ** 2`

Save the resulting numpy array as **bmi**.
Print out bmi.

In [19]:
weights = [90.0, 71.0, 120.0, 97.0, 99.2, 100,90, 100]
np_weight = np.array(weights)
# Calculate the BMI: bmi
np_weight/np_height_m**2

# Print out bmi

array([26.90977604, 20.09682617, 41.43470082, 31.57956326, 35.29850953,
       33.52082829, 23.52846669, 31.63271633])

In [20]:
len(np_weight)

8

### 2-D Arrays

Usually our data is made up of **columns** and **rows**, meaning our data is *multidimensional*

In [21]:
months = [1, 2, 3]
prices = [238.11, 237.81, 238.91]

In [22]:
cpi_array = np.array([months, prices])

In [23]:
cpi_array

array([[  1.  ,   2.  ,   3.  ],
       [238.11, 237.81, 238.91]])

Wait how do we index our array now??!

**array[row_index, column_index]**

In [24]:
#Insert Your Code Here
cpi_array[1, 2]

238.91

In [25]:
cpi_array[1, 0]

238.11

✨What do you think this slice represents? `cpi_array[:, 2]`

In [26]:
cpi_array[:, 2]

array([  3.  , 238.91])

In [27]:
cpi_array[:, 1]

array([  2.  , 237.81])

In [28]:
cpi_array[0, :]

array([1., 2., 3.])

Your Answer 

### Useful stuff we can do with numpy arrays

- np.mean()
- np.std()
- np.arrange()
- np.transpose() -> switches rows and columns
***
- np.shape
- np.size

**Question : what's the difference between `shape` and `size`?**

In [29]:
array = np.array([[1,2,3,4], [1230, 2445, 3455, 34656]])

In [30]:
array

array([[    1,     2,     3,     4],
       [ 1230,  2445,  3455, 34656]])

In [31]:
array.shape

(2, 4)

In [32]:
array.size

8

✨**Task**

We have two lists (months and earnings) in the following cell. perform the following steps in order:

- Create a 2D array of months and earnings and store in `arr`
- Print the shape of arr
- Print the size of arr
- Slice out the earnings and save it in `arr_earnings` (row 1, all values of columns)
- Calculate the mean of `arr_earnings`
- Transpose `arr` and print it

In [ ]:
months = [1,2,3,4,5]
earnings = [3200, 5677, 8928, 1298, 2390]








In [33]:
months = [1,2,3,4,5]
earnings = [3200, 5677, 8928, 1298, 2390]
#Insert your code here 
arr = np.array([months, earnings])
arr

array([[   1,    2,    3,    4,    5],
       [3200, 5677, 8928, 1298, 2390]])

In [34]:
print(arr.size)
arr.shape

10


(2, 5)

In [35]:
arr_earnings = arr[1]
arr_earnings

array([3200, 5677, 8928, 1298, 2390])

In [37]:
arr_earnings.mean()

4298.6

In [38]:
print(arr.transpose())

[[   1 3200]
 [   2 5677]
 [   3 8928]
 [   4 1298]
 [   5 2390]]


**Take aways from this notebook;**

- How to create numpy arrays
- How to sum numpy arrays
- How to use numpy arrays