### Introduction To Numpy 

#### Wait... why am I learning this again? I already know lists!

Untill now, we all know Python lists are powerful!
<ul>
    <li>They can hold collection of values</li>
    <li>They can hold different types of data</li>
    <li>We can change, add or remove the items inside of a list</li>
    </ul>
buttttt one important thing is missing.


**the ability to perform a mathematical operation over *all* the items at the same time**

Let's explore what I exactly mean by this.
We have the heights and weights of my family members right here:

In [1]:
heights = [1.73, 1.68, 1.79, 1.92, 1.50, 1.64]
weights = [90.0, 71.0, 55.0, 67.0, 99.2, 69]

If we want to calculate the BMI of each person, the fastest thing we hope that's gonna work would be the following:

In [2]:
weights/heights**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
weights[0]/heights[0]**2

oh oh :( Python has no idea what we're talking about. well no worries, that's why we have **Numpy**!

Numpy has its own array, which is an alternative for our regular Python lists. 
We simply call them **numpy arrays**


[in case you haven't installed numpy, run the following cell]

In [ ]:
!pip3 install numpy

In [3]:
import numpy as np

Let's *convert* our previous lists into numpy arrays and see if we can perform the one-liner in line2!

In [4]:
heights_np = np.array(heights)
heights_np

array([1.73, 1.68, 1.79, 1.92, 1.5 , 1.64])

In [5]:
weights_np = np.array(weights)
weights_np

array([90. , 71. , 55. , 67. , 99.2, 69. ])

In [6]:
weights_np/heights_np**2

array([30.07116843, 25.15589569, 17.16550669, 18.17491319, 44.08888889,
       25.6543724 ])

**Important Note : Numpy arrays can ONLY contain ONE data-type**

In [7]:
example = [2, 6.5, '4']

In [8]:
example_np = np.array(example)

In [9]:
example_np

array(['2', '6.5', '4'], dtype='<U32')

##### Sum of two numpy arrays

In [10]:
weights_np + heights_np

array([ 91.73,  72.68,  56.79,  68.92, 100.7 ,  70.64])

##### Numpy Array Subsetting

In [13]:
weights_np

[90.  71.  55.  67.  99.2 69. ]


In [12]:
weights_np[3]

67.0

#### Task 

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [15]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [16]:
#INSERT YOUR CODE HERE
np_height = np.array(baseball)

In [18]:
np_height_m = np_height/100

In [20]:
type(np_height_m)

numpy.ndarray

Use `np_height_m` and `np_weigh`t to calculate the **BMI** of each player. Use the following equation:
`weight/height ** 2`

Save the resulting numpy array as **bmi**.
Print out bmi.

In [21]:
weights = [90.0, 71.0, 120.0, 97.0, 99.2, 100,90, 100]
np_weight = np.array(weights)
# Calculate the BMI: bmi
# Print out bmi

In [22]:
np_weight

array([ 90. ,  71. , 120. ,  97. ,  99.2, 100. ,  90. , 100. ])

In [27]:
bmi = np_weight/np_height_m**2

In [28]:
bmi

array([27.77777778, 15.35965387, 27.21088435, 21.99546485, 28.06699864,
       32.28305785, 20.6039239 , 25.        ])

In [29]:
len(np_weight)

8

### 2-D Arrays

Usually our data is made up of **columns** and **rows**, meaning our data is *multidimensional*

In [30]:
months = [1, 2, 3]
prices = [238.11, 237.81, 238.91]

In [31]:
cpi_array = np.array([months, prices])

In [32]:
cpi_array

array([[  1.  ,   2.  ,   3.  ],
       [238.11, 237.81, 238.91]])

Wait how do we index our array now??!

**array[row_index, column_index]**

In [33]:
#Insert Your Code Here
cpi_array[1,1]

237.81

✨What do you think this slice represents? `cpi_array[:, 2]`

In [34]:
cpi_array[:, 2]

array([  3.  , 238.91])

In [35]:
cpi_array[:, 1]

array([  2.  , 237.81])

In [36]:
cpi_array[0, :]

array([1., 2., 3.])

In [39]:
cpi_array[:,0]

array([  1.  , 238.11])

Your Answer 

### Useful stuff we can do with numpy arrays

- np.mean()
- np.std()
- np.arange()
- np.transpose() -> switches rows and columns
***
- np.shape
- np.size

In [47]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

**Question : what's the difference between `shape` and `size`?**

In [40]:
array = np.array([[1,2,3,4], [1230, 2445, 3455, 34656]])

In [42]:
array.shape

(2, 4)

In [43]:
array.size

8

In [44]:
array?
type(array)

numpy.ndarray

✨**Task**

We have two lists (months and earnings) in the following cell. perform the following steps in order:

- Create a 2D array of months and earnings and store in `arr`
- Print the shape of arr
- Print the size of arr
- Slice out the earnings and save it in `arr_earnings` (row 1, all values of columns)
- Calculate the mean of `arr_earnings`
- Transpose `arr` and print it

In [ ]:
months = [1,2,3,4,5]
earnings = [3200, 5677, 8928, 1298, 2390]

#INSERT YOUR CODE HERE







**Take aways from this notebook;**

- How to create numpy arrays
- How to sum numpy arrays
- How to use numpy arrays